### ISSUE TITLE
horizontal zoom not working as individual

### ISSUE THREAD

**Issue by keskink** [SunPointed/MPFlutterChart#107]
horizontal zoom not working as individual even when pinchZoomEnabled: false
it is zooming proportional when I try to zoom horizontal.
But vertical zooming working individual.

**Comment by SunPointed** [comment]
I test barchart basic and it horizontal zoom worked. what chart you used?

**Comment by keskink** [comment]
I am using Linechart

**Comment by SunPointed** [comment]
make sure this value is set scaleXEnabled: true

**Comment by SunPointed** [comment]
Hi ,I see you video it seems the touch conflict in vertical direction with Chart and ScrollView. you can set resolveGestureVerticalConflict to true but it will let Chart consume the touch event in chart area. In flutter current no have a solution to solve touch event conflict when parent and child need event in same direction. You can see  [https://github.com/flutter/flutter/issues/50946#issuecomment-644629110](url), sorry for taht.

**Comment by keskink** [comment]
[LineChart_ZoomingProblem.zip](https://github.com/SunPointed/MPFlutterChart/files/4813821/LineChart_ZoomingProblem.zip)
Hi,
Unfortunately, I don't agree to you. Please watch two video as attached. One of android version. it is working good. One is flutter version, horizontal zooming not working proper.

**Comment by keskink** [comment]
> Hi ,I see you video it seems the touch conflict in vertical direction with Chart and ScrollView. you can set resolveGestureVerticalConflict to true but it will let Chart consume the touch event in chart area. In flutter current no have a solution to solve touch event conflict when parent and child need event in same direction. You can see [https://github.com/flutter/flutter/issues/50946#issuecomment-644629110](url), sorry for that.

I can not reach this link too.

**Comment by SunPointed** [comment]
@keskink  Hi， I see the video you provided, I find the scale direction can change in x and y direction in a single zoom action. I tried to make it change only one direction in a single zoom action.  Please take look at Line Chart Cubic Demo, if you still find any problem, can you provider video by this demo for me easy to debug? thanks

**Comment by keskink** [comment]
First of all, many thanks to your quick interest.
and many thanks to your fixes. How can I get your fixes?

And be sure that I can provide anything you need to fix any issue.
btw. I look at to Line Chart Cubic Demo, that is my expeted behavior.
Thanks again

**Comment by keskink** [comment]
Hello, I downloaded project from git. And test it. Basic (Simple line chart) and, Cucib is working well

**Comment by SunPointed** [comment]
@keskink  I released 0.2.2 , you can have a try

**Comment by keskink** [comment]
unfortunately same. horizontal zooming not working like vertical.

**Comment by keskink** [comment]
I created a test project for you. my issue still exists.

Thanks in advance.


[mpcharttest.zip](https://github.com/SunPointed/MPFlutterChart/files/4878587/mpcharttest.zip)

**Comment by keskink** [comment]
I am still waiting response from you. 
Do you need re open this issue?

**Comment by keskink** [comment]
I am still waiting.
